{
 "title": "vLLM Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "vLLM Iterations Token",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vllm:iteration_tokens_total_count"
    }
   ]
  },
  {
   "title": "vLLM Generations Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "vllm:generation_tokens_total" }
   ]
  },
  {
   "title": "vLLM Time Per Output Token",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "vllm:time_per_output_token_seconds_count"
    }
   ]
  },
  {
   "title": "vLLM Time to First Token Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "vllm:time_to_first_token_seconds_count"
    }
   ]
  },
  {
   "title": "vLLM Time in Queue Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "vllm:time_in_queue_requests_count"
    }
   ]
  },
  {
   "title": "vLLm Request Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "vllm:request_prompt_tokens_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vLLm Request Inference Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "vllm:request_inference_time_seconds_count"
    }
   ]
  },
  {
   "title": "vLLM Num Preemptions Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "vllm:num_preemptions_total" }
   ]
  }
 ]
}